core/urls.py
from django.urls import path
from django.views.generic.dates import ArchiveIndexView

from core.models import Article

from .views import (
    index,
    blog,
    cart,
    category,
    checkout,
    contact,
    elements,
    singleblog,
    singleproduct,
    tracking,

    OrderSummaryView,
    ItemDetailView,
    add_to_cart,
    AddCouponView,
    remove_from_cart,
    remove_single_item_from_cart,
    PaymentView,
    RequestRefundView

)

app_name= 'core'

urlpatterns = [
    path('', index, name='index'),
    path('blog/', blog, name='blog'),
    path('cart/', cart, name='cart'),
    path('category/', category, name='category'),
    path('checkout/', checkout, name='checkout'),
    path('contact/', contact, name='contact'),
    path('elements/', elements, name='elements'),
    path('singleblog/<int:id>/', singleblog, name='singleblog'),
    path('single-product/', singleproduct, name='singleproduct'),
    path('tracking/', tracking, name='tracking'),

    path('archive/', ArchiveIndexView.as_view(model=Article, date_field="pub_date"), name="article_archive"),

    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund')   
]

djecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <link rel="icon" href="{% static 'img/favicon.png' %}" type="image/png" />
  <title>Eiser ecommerce</title>
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />
  <link rel="stylesheet" href="{% static 'vendors/linericon/style.css' %}" />
  <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />
  <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}" />
  <link rel="stylesheet" href="{% static 'css/flaticon.css' %}" />
  <link rel="stylesheet" href="{% static 'vendors/owl-carousel/owl.carousel.min.css' %}" />
  <link rel="stylesheet" href="{% static 'vendors/lightbox/simpleLightbox.css' %}" />
  <link rel="stylesheet" href="{% static 'vendors/nice-select/css/nice-select.css' %}" />
  <link rel="stylesheet" href="{% static 'vendors/animate-css/animate.css' %}" />
  <link rel="stylesheet" href="{% static 'vendors/jquery-ui/jquery-ui.css' %}" />
  <!-- main css -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  <link rel="stylesheet" href="{% static 'css/responsive.css' %}" />
</head>

<header class="header_area">
    <div class="top_menu">
        <div class="container">
            <div class="row">
                <div class="col-lg-7">
                    <div class="float-left">
                        <p>Phone: +01 256 25 235</p>
                        <p>email: info@eiser.com</p>
                    </div>
                </div>
                <div class="col-lg-5">
                    <div class="float-right">
                        <ul class="right_side">
                            <li>
                                <a href="{% url 'core:cart' %}">
                                    gift card
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'core:tracking' %}">
                                    track order
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'core:contact' %}">
                                    Contact Us
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="main_menu">
        <div class="container">
            {% include "navbar.html" %}
        </div>
    </div>
</header>
<body>
    {% block content %}
    {% endblock content %}

    {% block extra_body %}
    {% endblock %}

    {% include "footer.html" %}
    {% include "scripts.html" %}

    {% block extra_scripts %}
    {% endblock extra_scripts %}
</body>
</html>

templates/category.html
{% extends "base.html" %}
{% block content %}
    <!--================Category Product Area =================-->
    <section class="cat_product_area section_gap">
      <div class="container">
        <div class="row flex-row-reverse">
          <div class="col-lg-9">
            <div class="product_top_bar">
              <div class="left_dorp">
                <select class="sorting">
                  <option value="1">Default sorting</option>
                  <option value="2">Default sorting 01</option>
                  <option value="4">Default sorting 02</option>
                </select>
                <select class="show">
                  <option value="1">Show 12</option>
                  <option value="2">Show 14</option>
                  <option value="4">Show 16</option>
                </select>
              </div>
            </div>
            
            <!-- PRODUCT CARD -->

            <div class="latest_product_inner">
              <div class="row">
                <div class="col-lg-4 col-md-6">
                  <div class="single-product">
                    <div class="product-img">
                      <img
                        class="card-img"
                        {# src="{% static 'img/product/inspired-product/i1.jpg' %}" #}
                        alt=""
                      />
                      <div class="p_icon">
                        <a href="#">
                          <i class="ti-eye"></i>
                        </a>
                        <a href="#">
                          <i class="ti-heart"></i>
                        </a>
                        <a href="#">
                          <i class="ti-shopping-cart"></i>
                        </a>
                      </div>
                    </div>
                    <div class="product-btm">
                      <a href="#" class="d-block">
                        <h4>Latest men’s sneaker</h4>
                      </a>
                      <div class="mt-3">
                        <span class="mr-4">$25.00</span>
                        <del>$35.00</del>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

            <!-- END -->

          <div class="col-lg-3">
            <div class="left_sidebar_area">
              <aside class="left_widgets p_filter_widgets">
                <div class="l_w_title">
                  <h3>Browse Categories</h3>
                </div>
                <div class="widgets_inner">
                  <ul class="list">
                    <li>
                      <a href="#">Frozen Fish</a>
                    </li>
                    <li>
                      <a href="#">Dried Fish</a>
                    </li>
                    <li>
                      <a href="#">Fresh Fish</a>
                    </li>
                    <li>
                      <a href="#">Meat Alternatives</a>
                    </li>
                    <li>
                      <a href="#">Fresh Fish</a>
                    </li>
                    <li>
                      <a href="#">Meat Alternatives</a>
                    </li>
                    <li>
                      <a href="#">Meat</a>
                    </li>
                  </ul>
                </div>
              </aside>

              <aside class="left_widgets p_filter_widgets">
                <div class="l_w_title">
                  <h3>Product Brand</h3>
                </div>
                <div class="widgets_inner">
                  <ul class="list">
                    <li>
                      <a href="#">Apple</a>
                    </li>
                    <li>
                      <a href="#">Asus</a>
                    </li>
                    <li class="active">
                      <a href="#">Gionee</a>
                    </li>
                    <li>
                      <a href="#">Micromax</a>
                    </li>
                    <li>
                      <a href="#">Samsung</a>
                    </li>
                  </ul>
                </div>
              </aside>

              <aside class="left_widgets p_filter_widgets">
                <div class="l_w_title">
                  <h3>Color Filter</h3>
                </div>
                <div class="widgets_inner">
                  <ul class="list">
                    <li>
                      <a href="#">Black</a>
                    </li>
                    <li>
                      <a href="#">Black Leather</a>
                    </li>
                    <li class="active">
                      <a href="#">Black with red</a>
                    </li>
                    <li>
                      <a href="#">Gold</a>
                    </li>
                    <li>
                      <a href="#">Spacegrey</a>
                    </li>
                  </ul>
                </div>
              </aside>

              <aside class="left_widgets p_filter_widgets">
                <div class="l_w_title">
                  <h3>Price Filter</h3>
                </div>
                <div class="widgets_inner">
                  <div class="range_item">
                    <div id="slider-range"></div>
                    <div class="">
                      <label for="amount">Price : </label>
                      <input type="text" id="amount" readonly />
                    </div>
                  </div>
                </div>
              </aside>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!--================End Category Product Area =================-->
{% endblock content %}
   

templates/checkout.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

  <main >
    <div class="container wow fadeIn">
      <h2 class="my-5 h2 text-center">Checkout form</h2>
      <div class="row">
        <div class="col-md-8 mb-4">
          <div class="card">
            <form method="POST" class="card-body">
              {% csrf_token %}

              <h3>Shipping address</h3>

              <div class='hideable_shipping_form'>

                <div class="md-form mb-5">
                  <input type='text' placeholder='1234 Main St' id='shipping_address' name='shipping_address' class='form-control' />
                  <label for="shipping_address" class="">Address</label>
                </div>

                <div class="md-form mb-5">
                  <input type='text' placeholder='Apartment or suite' id='shipping_address2' name='shipping_address2' class='form-control' />
                  <label for="shipping_address2" class="">Address 2 (optional)</label>
                </div>

                <div class="row">
                  <div class="col-lg-4 col-md-12 mb-4">
                    <label for="country">Country</label>
                    {{ form.shipping_country }}
                    <div class="invalid-feedback">
                      Please select a valid country.
                    </div>
                  </div>
                  <div class="col-lg-4 col-md-6 mb-4">
                    <label for="shipping_zip">Zip</label>
                    <input type='text' placeholder='Zip code' id='shipping_zip' name='shipping_zip' class='form-control' />
                    <div class="invalid-feedback">
                      Zip code required.
                    </div>
                  </div>
                </div>

                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input" name="same_billing_address" id="same_billing_address">
                  <label class="custom-control-label" for="same_billing_address">Billing address is the same as my shipping address</label>
                </div>
                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input" name="set_default_shipping" id="set_default_shipping">
                  <label class="custom-control-label" for="set_default_shipping">Save as default shipping address</label>
                </div>

              </div>

              {% if default_shipping_address %}
              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="use_default_shipping" id="use_default_shipping">
                <label class="custom-control-label" for="use_default_shipping">Use default shipping address: {{ default_shipping_address.street_address|truncatechars:10 }}</label>
              </div>
              {% endif %}

              <hr>

              <h3>Billing address</h3>

              <div class='hideable_billing_form'>
                <div class="md-form mb-5">
                  <input type='text' placeholder='1234 Main St' id='billing_address' name='billing_address' class='form-control' />
                  <label for="billing_address" class="">Address</label>
                </div>

                <div class="md-form mb-5">
                  <input type='text' placeholder='Apartment or suite' id='billing_address2' name='billing_address2' class='form-control' />
                  <label for="billing_address2" class="">Address 2 (optional)</label>
                </div>

                <div class="row">
                  <div class="col-lg-4 col-md-12 mb-4">
                    <label for="country">Country</label>
                    {{ form.billing_country }}
                    <div class="invalid-feedback">
                      Please select a valid country.
                    </div>
                  </div>

                  <div class="col-lg-4 col-md-6 mb-4">
                    <label for="billing_zip">Zip</label>
                    <input type='text' placeholder='Zip code' id='billing_zip' name='billing_zip' class='form-control' />
                    <div class="invalid-feedback">
                      Zip code required.
                    </div>
                  </div>

                </div>

                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input" name="set_default_billing" id="set_default_billing">
                  <label class="custom-control-label" for="set_default_billing">Save as default billing address</label>
                </div>

              </div>

              {% if default_billing_address %}
              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="use_default_billing" id="use_default_billing">
                <label class="custom-control-label" for="use_default_billing">Use default billing address: {{ default_billing_address.street_address|truncatechars:10 }}</label>
              </div>
              {% endif %}
              <hr>

              <h3>Payment option</h3>

              <div class="d-block my-3">
                {% for value, name in form.fields.payment_option.choices %}
                <div class="custom-control custom-radio">
                  <input id="{{ name }}" name="payment_option" value="{{ value }}" type="radio" class="custom-control-input" required>
                  <label class="custom-control-label" for="{{ name }}">{{ name }}</label>
                </div>
                {% endfor %}
              </div>

              <hr class="mb-4">
              <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>

            </form>

          </div>

        </div>

        <div class="col-md-4 mb-4">
          {% include "order_snippet.html" %}
        </div>

      </div>

    </div>
  </main>

{% endblock content %}

{% block extra_scripts %}
<script>
var hideable_shipping_form = $('.hideable_shipping_form');
var hideable_billing_form = $('.hideable_billing_form');

var use_default_shipping = document.querySelector("input[name=use_default_shipping]");
var use_default_billing = document.querySelector("input[name=use_default_billing]");

use_default_shipping.addEventListener('change', function() {
  if (this.checked) {
    hideable_shipping_form.hide();
  } else {
    hideable_shipping_form.show();
  }
})

use_default_billing.addEventListener('change', function() {
  if (this.checked) {
    hideable_billing_form.hide();
  } else {
    hideable_billing_form.show();
  }
})

</script>
{% endblock extra_scripts %}

templates/footer.html
<footer class="footer-area section_gap">
    <div class="container">
        <div class="row">
            <div class="col-lg-2 col-md-6 single-footer-widget">
                <h4>Top Products</h4>
                <ul>
                    <li><a href="#">Managed Website</a></li>
                    <li><a href="#">Manage Reputation</a></li>
                    <li><a href="#">Power Tools</a></li>
                    <li><a href="#">Marketing Service</a></li>
                </ul>
            </div>
            <div class="col-lg-2 col-md-6 single-footer-widget">
                <h4>Quick Links</h4>
                <ul>
                    <li><a href="#">Jobs</a></li>
                    <li><a href="#">Brand Assets</a></li>
                    <li><a href="#">Investor Relations</a></li>
                    <li><a href="#">Terms of Service</a></li>
                </ul>
            </div>
            <div class="col-lg-2 col-md-6 single-footer-widget">
                <h4>Features</h4>
                <ul>
                    <li><a href="#">Jobs</a></li>
                    <li><a href="#">Brand Assets</a></li>
                    <li><a href="#">Investor Relations</a></li>
                    <li><a href="#">Terms of Service</a></li>
                </ul>
            </div>
            <div class="col-lg-2 col-md-6 single-footer-widget">
                <h4>Resources</h4>
                <ul>
                    <li><a href="#">Guides</a></li>
                    <li><a href="#">Research</a></li>
                    <li><a href="#">Experts</a></li>
                    <li><a href="#">Agencies</a></li>
                </ul>
            </div>
            <div class="col-lg-4 col-md-6 single-footer-widget">
                <h4>Newsletter</h4>
                <p>You can trust us. we only send promo offers,</p>
                <div class="form-wrap" id="mc_embed_signup">
                    <form target="_blank" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
                        method="get" class="form-inline">
                        <input class="form-control" name="EMAIL" placeholder="Your Email Address" onfocus="this.placeholder = ''"
                            onblur="this.placeholder = 'Your Email Address '" required="" type="email">
                        <button class="click-btn btn btn-default">Subscribe</button>
                        <div style="position: absolute; left: -5000px;">
                            <input name="b_36c4fd991d266f23781ded980_aefe40901a" tabindex="-1" value="" type="text">
                        </div>
                        <div class="info"></div>
                    </form>
                </div>
            </div>
        </div>
        <div class="footer-bottom row align-items-center">
            <p class="footer-text m-0 col-lg-8 col-md-12">
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            </p>
            <div class="col-lg-4 col-md-12 footer-social">
                <a href="#"><i class="fa fa-facebook"></i></a>
                <a href="#"><i class="fa fa-twitter"></i></a>
                <a href="#"><i class="fa fa-dribbble"></i></a>
                <a href="#"><i class="fa fa-behance"></i></a>
            </div>
        </div>
    </div>
</footer>

templates/index.html
{% extends "base.html" %}
{% block content %}
<!--================Home Banner Area =================-->
<section class="home_banner_area mb-40">
    <div class="banner_inner d-flex align-items-center">
        <div class="container">
            <div class="banner_content row">
                <div class="col-lg-12">
                    <p class="sub text-uppercase">men Collection</p>
                    <h3><span>Show</span> Your <br />Personal <span>Style</span></h3>
                    <h4>Fowl saw dry which a above together place.</h4>
                    <a class="main_btn mt-40" href="#">View Collection</a>
                </div>
            </div>
        </div>
    </div>
</section>
<!--================End Home Banner Area =================-->
<!-- Start feature Area -->
<section class="feature-area section_gap_bottom_custom">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6">
                <div class="single-feature">
                    <a href="#" class="title">
                        <i class="flaticon-money"></i>
                        <h3>Money back gurantee</h3>
                    </a>
                    <p>Shall open divide a one</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="single-feature">
                    <a href="#" class="title">
                        <i class="flaticon-truck"></i>
                        <h3>Free Delivery</h3>
                    </a>
                    <p>Shall open divide a one</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="single-feature">
                    <a href="#" class="title">
                        <i class="flaticon-support"></i>
                        <h3>Alway support</h3>
                    </a>
                    <p>Shall open divide a one</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="single-feature">
                    <a href="#" class="title">
                        <i class="flaticon-blockchain"></i>
                        <h3>Secure payment</h3>
                    </a>
                    <p>Shall open divide a one</p>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- End feature Area -->
<!--================ Start Blog Area =================-->
<section class="blog-area section-gap">
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-12">
            <div class="main_title">
                <h2><span>latest blog</span></h2>
                <p>Bring called seed first of third give itself now ment</p>
            </div>
        </div>
    </div>
    <div class="row">
        {% for blog in blogs %}
        <div class="col-lg-4 col-md-6">
            <div class="single-blog">
                <div class="thumb">
                    <img class="img-fluid" src="{{ blog.image.url }}" alt=""> 
                </div>
                <div class="short_details">
                    <div class="meta-top d-flex">
                        <a href="#">By Admin</a>
                        <a href="#"><i class="ti-comments-smiley"></i>2 Comments</a>
                    </div>
                    <a class="d-block" href="{% url 'core:singleblog' blog.id %}">
                        <h4>{{ blog.title }}</h4>
                    </a>
                    <div class="text-wrap">
                        <p>{{ blog.preview }}</p>
                    </div>
                    <a href="#" class="blog_btn">Learn More <span class="ml-2 ti-arrow-right"></span></a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<!--================ End Blog Area =================-->
{% endblock content %}

templates/order_snippet.html
<div class="col-md-12 mb-4">
    <h4 class="d-flex justify-content-between align-items-center mb-3">
    <span class="text-muted">Your cart</span>
    <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
    </h4>
    <ul class="list-group mb-3 z-depth-1">
    {% for order_item in order.items.all %}
    <li class="list-group-item d-flex justify-content-between lh-condensed">
        <div>
        <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.title}}</h6>
        <small class="text-muted">{{ order_item.item.description}}</small>
        </div>
        <span class="text-muted">${{ order_item.get_final_price }}</span>
    </li>
    {% endfor %}
    {% if order.coupon %}
    <li class="list-group-item d-flex justify-content-between bg-light">
        <div class="text-success">
        <h6 class="my-0">Promo code</h6>
        <small>{{ order.coupon.code }}</small>
        </div>
        <span class="text-success">-${{ order.coupon.amount }}</span>
    </li>
    {% endif %}
    <li class="list-group-item d-flex justify-content-between">
        <span>Total (USD)</span>
        <strong>${{ order.get_total }}</strong>
    </li>
    </ul>

    {% if DISPLAY_COUPON_FORM %}
    <form class="card p-2" action="{% url 'core:add-coupon' %}" method="POST">
        {% csrf_token %}
        <div class="input-group">
            {{ couponform.code }}
            <div class="input-group-append">
            <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
            </div>
        </div>
    </form>
    {% endif %}

</div>

templates/order_summary.html
{% extends "base.html" %}

{% block content %}
  <main>
    <div class="container">

    <div class="table-responsive text-nowrap">
    <h2>Order Summary</h2>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Item title</th>
            <th scope="col">Price</th>
            <th scope="col">Quantity</th>
            <th scope="col">Total Item Price</th>
        </tr>
        </thead>
        <tbody>
        {% for order_item in object.items.all %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ order_item.item.title }}</td>
            <td>{{ order_item.item.price }}</td>
            <td>
                <a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}"><i class="fas fa-minus mr-2"></i></a>
                {{ order_item.quantity }}
                <a href="{% url 'core:add-to-cart' order_item.item.slug %}"><i class="fas fa-plus ml-2"></i></a>
            </td>
            <td>
            {% if order_item.item.discount_price %}
                ${{ order_item.get_total_discount_item_price }}
                <span class="badge badge-primary">Saving ${{ order_item.get_amount_saved }}</span>
            {% else %}
                ${{ order_item.get_total_item_price }}
            {% endif %}
            <a style='color: red;' href="{% url 'core:remove-from-cart' order_item.item.slug %}">
                <i class="fas fa-trash float-right"></i>
            </a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan='5'>Your cart is empty</td>
        </tr>
        <tr>
            <td colspan="5">
            <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
            </td>
        </tr>
        {% endfor %}
        {% if object.coupon %}
        <tr>
            <td colspan="4"><b>Coupon</b></td>
            <td><b>-${{ object.coupon.amount }}</b></td>
        </tr>
        {% endif %}
        {% if object.get_total %}
        <tr>
            <td colspan="4"><b>Order Total</b></td>
            <td><b>${{ object.get_total }}</b></td>
        </tr>
        <tr>
            <td colspan="5">
            <a class='btn btn-warning float-right ml-2' href='/checkout/'>Proceed to checkout</a>
            <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
            </td>
        </tr>
        {% endif %}
        </tbody>
    </table>

    </div>

    </div>
  </main>

{% endblock content %}

templates/request_refund.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <main>
    <div class="container">

    <h2>Request Refund</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class='btn btn-primary'>Submit</button>
    </form>

    </div>
  </main>

{% endblock content %}

templates/scripts.html
{% load static %}
<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'js/popper.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/stellar.js' %}"></script>
<script src="{% static 'vendors/lightbox/simpleLightbox.min.js' %}"></script>
<script src="{% static 'vendors/nice-select/js/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'vendors/isotope/imagesloaded.pkgd.min.js' %}"></script>
<script src="{% static 'vendors/isotope/isotope-min.js' %}"></script>
<script src="{% static 'vendors/owl-carousel/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
<script src="{% static 'vendors/counter-up/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'vendors/counter-up/jquery.counterup.js' %}"></script>
<script src="{% static 'js/mail-script.js' %}"></script>
<script src="{% static 'js/theme.js' %}"></script>
<script type="text/javascript">
    $(document).ready(function() { $('.counter').counterUp();} );
</script>